### ISSUE TITLE
Using SR.jl types in conjunction with DE.jl

### ISSUE THREAD

**Issue by tomkimpson** [milankl/StochasticRounding.jl#57]
```julia
using DifferentialEquations
using StochasticRounding
f = (u,p,t) -> (p*u)
prob_ode_linear = ODEProblem(f,Float32sr(1.0)/Float32sr(2.0),(Float32sr(0.0),Float32sr(1.0)),Float32sr(1.01));
sol =solve(prob_ode_linear,Tsit5())
```

Throws a `MethodError: no method matching Float32sr(::BigFloat)`

Discussed on Slack - may be able to do something similar to how BigFloats are handled in https://github.com/milankl/SoftPosit.jl

**Comment by milankl** [comment]
I believe this issue is similar https://github.com/milankl/SoftPosit.jl/issues/65, the BigFloat conversion is no problem to add, with the other methods I want to be a bit more careful.
