### ISSUE TITLE
Restructure

### ISSUE THREAD

**Issue by milankl** [milankl/StochasticRounding.jl#70]
At the moment we have a lot of code redundancy, meaning for every missing method we have implement separate methods for each of the (currently) 4 stochastic rounding formats. This issue could be resolved by

1) subtyping

```julia
abstract type AbstractStochasticFloat <: AbstractFloat end
primitive type Float32sr <: AbstractStochasticFloat 32 end
```
with
```julia
float(::Type{Float32sr}) = Float32
stochastic_float(::Type{Float32}) = Float32sr
widen(::Type{Float32}) = Float64    # used for exact arithmetic
```
to define the corresponding stochastic-deterministic types.

2) general `stochastic_round` function

Every new stochastic format then implements
```julia
stochastic_round(::Type{<:AbstractStochasticFloat},x::AbstractFloat)
```
for example
```julia
stochastic_round(::Type{Float32sr},x::Float64) = ...
```

3) methods for stochastic floats

should then be defined once, e.g.
```julia
method(x::T) where {T<:AbstractStochasticFloat} = T(method(float(T)(x)))
method(::Type{T}) where {T<:AbstractStochasticFloat} = method(float(T))
method(x::T,y::T) where {T<:AbstractStochasticFloat} = T(method(widen(T)(x),widen(T)(y)))
```

**Comment by milankl** [comment]
@avleenk2312 something for the future, or if one of us is bored ... 😆

**Comment by avleenk2312** [comment]
Apologies the "cone of silence" over the last few days, I had been sick. It all sounds good! I'd be happy to take a look at these issues. 🙂

**Comment by avleenk2312** [comment]
Apologies for the "cone of silence" over the past days, I had been sick. I'll be happy to take a look at these issues. And, the other ones that were closed/reopened over the past days. 🙂
